# Generated by Django 4.2.1 on 2023-05-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('rut', models.CharField(default='', max_length=100)),
                ('correo', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', null=True, upload_to='avatars')),
                ('grupo', models.CharField(default='Artista Novato', max_length=100)),
                ('descripcion', models.TextField(default='Sin descripcion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('historia', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('precio', models.IntegerField(default=0)),
                ('foto', models.ImageField(default='', null=True, upload_to='obras')),
                ('estado', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='Sin Comentarios')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webGrupoCero.categoria')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webGrupoCero.tecnica')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_1', models.ImageField(upload_to='galeria')),
                ('foto_2', models.ImageField(upload_to='galeria')),
                ('foto_3', models.ImageField(upload_to='galeria')),
                ('angulo_1', models.CharField(default='Frontal', max_length=100)),
                ('angulo_2', models.CharField(default='Lateral', max_length=100)),
                ('angulo_3', models.CharField(default='Trasero', max_length=100)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webGrupoCero.obra')),
            ],
        ),
    ]
